allow_public_access:
  name: allow_public_access
  setting_type: system
  value: 1
  item_type: bool

theme:
  name: theme
  setting_type: Hidden
  value: fracture
  item_type: string

list_type:
  name: list_type
  setting_type: Hidden
  value: detailed
  item_type: string

site_title:
  name: site_title
  setting_type: Public
  value: website title
  item_type: string

item_page_type:
  name: item_page_type
  setting_type: Hidden
  value: summarized
  item_type: string

max_items_per_user:
  name: max_items_per_user
  setting_type: Item
  value: 0
  item_type: string

list_type:
  name: list_type
  setting_type: Hidden
  value: detailed
  item_type: string
